version: "3.9"
name: vault-terraform-sandbox
services:
  vault-transit:
    build:
      context: vault
    cap_add:
      - IPC_LOCK
    volumes:
        - ${PWD}/vault/config/vault-transit.hcl.template:/vault/config/vault.hcl.template:r
    command: vault server --dev
    environment:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_DEV_ROOT_TOKEN_ID: transit-engine-bypass
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_TOKEN: transit-engine-bypass
    healthcheck:
      test: vault read transit/keys/unseal_key
      interval: "5s"
  
  vault:
    depends_on:
      vault-transit:
        condition: service_healthy
    build:
      context: vault
    cap_add:
      - IPC_LOCK
    volumes:
        - ${PWD}/vault/config/vault.hcl.template:/vault/config/vault.hcl.template:r
        - ${PWD}/terraform/policies/vault-operator.hcl:/vault/policies/vault-operator.hcl:r
    command: vault server -config=/vault/config/vault.hcl
    deploy:
      replicas: 1
    environment:
      VAULT_ADDR: "http://localhost:8200"
      VAULT_TRANSIT_TOKEN: "transit-engine-bypass"
    healthcheck:
      test: vault read /sys/health
      interval: "5s"

  vault-operator:
    depends_on:
      vault:
        condition: service_healthy
    build: 
      context: operator
    volumes:
      - ${PWD}/terraform:/terraform
    environment:
      VAULT_ADDR: http://vault:8200
      TERRAFORM_VAULT_USERNAME: vault-operator
      TERRAFORM_VAULT_PASSWORD: vault-operator

  vault-ui:
    depends_on:
      vault:
        condition: service_healthy
    build:
      context: nginx
    ports:
      - "8080:8080"
