version: "3.9"
services:
  generate-tls-certs:
    build:
      context: ./cfssl
    volumes:
      - vault-ca-tls:/tmp/tls/ca
      - vault-node-tls:/tmp/tls/vault-node
      - vault-operator-tls:/tmp/tls/vault-operator
    working_dir: /tmp/tls
  vault:
    depends_on:
    - generate-tls-certs
    container_name: vault
    image: hashicorp/vault:latest
    cap_add:
      - IPC_LOCK
    volumes:
        - vault-file:/vault/file:rw
        - ${PWD}/vault/config:/vault/config:r
        - ${PWD}/vault/logs:/vault/logs:rw
        - vault-node-tls:/etc/ssl/vault-node
        - vault-ca-tls:/etc/ssl/vault-ca
    environment:
        - VAULT_ADDR=https://localhost:8200
        - VAULT_CAPATH=/etc/ssl/vault-ca/ca.pem
        - VAULT_CLIENT_CERT=/etc/ssl/vault-node/vault.pem
        - VAULT_CLIENT_KEY=/etc/ssl/vault-node/vault-key.pem
    ports:
      - 8200:8200
    command: vault server -config=/vault/config/vault.hcl
  operator:
    depends_on:
    - generate-tls-certs
    container_name: vault-operator
    build: 
      context: ./operator
    environment:
        - VAULT_ADDR=https://vault:8200
        - VAULT_CAPATH=/etc/ssl/vault-ca/ca.pem
        - VAULT_CLIENT_CERT=/etc/ssl/vault-operator/vault.pem
        - VAULT_CLIENT_KEY=/etc/ssl/vault-operator/vault-key.pem
    volumes:
        - vault-operator-tls:/etc/ssl/vault-operator
        - vault-ca-tls:/etc/ssl/vault-ca
        - ${PWD}/terraform:/terraform
    command: [ "./unseal.sh && sleep 1d" ]

volumes:
  vault-file: {}
  vault-ca-tls: {}
  vault-node-tls: {}
  vault-operator-tls: {}
